name: Mac make CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: configure
      run: arch -arm64 ./configure
    - name: make
      run: arch -arm64 make -j4
    - name: make tests
      run: arch -arm64 make -C tests
    - name: run tests
      run:  pushd tests;arch -arm64 ./test;popd
    - name: make minimal sample
      run: arch -arm64 make -C samples/minimal -f makefile.unx clean;arch -arm64 make -C samples/minimal -f makefile.unx
